config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
      delete :cancel_vote
    end
  end

  concern :commentable do
    resources :comments, only: %i[create destroy], shallow: true
  end

  resources :questions, concerns: %i[votable commentable] do
    resources :answers, concerns: %i[votable commentable], except: :index, shallow: true do
      member do
        patch :best
      end
    end
    resources :subscriptions, only: %i[create destroy], shallow: true
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: %i[index destroy]

  root to: "questions#index"

  get '/email', to: 'users#email'
  post '/set_email', to: 'users#set_email'

  get '/search', to: 'search#search'

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
        resources :users, only: :index do
            get :me, on: :collection
        end

        resources :questions, only: %i[index show create update destroy] do
          resources :answers, only: %i[index show create update destroy], shallow: true
        end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many :subscriptions, dependent: :destroy
  has_one :reward, dependent: :destroy

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :reward, reject_if: :all_blank, allow_destroy: true

  belongs_to :best_answer, class_name: 'Answer', optional: true
  belongs_to :user

  validates :title, :body, presence: true

  after_create :subscribe_author

  scope :created_in_a_day, -> { where("created_at >= :today", today: DateTime.current.beginning_of_day) }

  def other_answers
    best_answer ? answers.where.not(id: best_answer_id) : answers
  end

  private

  def subscribe_author
    subscriptions.create!(user: user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :load_question, only: %i[show update destroy]

  authorize_resource

  def index
    @questions = Question.all
    render json: @questions, each_serializer: QuestionsSerializer
  end

  def show
    render json: @question, each_serializer: QuestionSerializer
  end

  def create
    @question = current_resource_owner.questions.new(question_params)

    if @question.save
      render json: @question
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def update
    if @question.update(question_params)
      render json: @question
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    if @question.destroy
      render json: @question
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, links_attributes: %i[name url id],
                                                    reward_attributes: %i[title image])
  end

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include ActiveStorage::SetCurrent
  include Voted

  before_action :authenticate_user!, except: %w[index show]
  before_action :load_question, only: %w[show update destroy]

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    @new_answer = @question.answers.new
    @new_answer.links.new
    gon.question_id = @question.id
  end

  def new
    @question = current_user.questions.new
    @question.links.new
    @question.build_reward
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question
      publish_question('add')
    else
      @question.build_reward
      render :new
    end
  end

  def update
    return unless @question.update(question_params.except(:files))

    attach_files(@question)
    flash[:notice] = 'Your question was successfully updated.'
    publish_question('update')
  end

  def destroy
    @question.best_answer.unmark_as_best if @question.best_answer

    @question.destroy
    redirect_to questions_path, notice: 'Your question was successfully deleted.'
    publish_question('destroy')
  end

  private

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [], links_attributes: %i[name url id _destroy],
                                     reward_attributes: %i[title image _destroy])
  end

  def attach_files(question)
    question.files.attach(params[:question][:files]) if params[:question][:files].present?
  end

  def publish_question(event)
    return if @question.errors.any?
    url = @question.reward.image.url if @question.reward

    ActionCable.server.broadcast(
      'questions',
      question: @question,
      reward: @question.reward.as_json,
      url: url,
      event: event
    )
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_edit_form.html.slim
= form_with model: question, local: false, html: { id: 'edit-question' }, class: 'd-none' do |f|
  = render 'form_fields', f: f

  p Assign reward:
  - unless question.reward.present?
    - question.build_reward
  p
    = render 'rewards/form', f: f

  div class='btn-group' role='group'
    = f.submit 'Save', class: 'btn btn-success btn-sm'
    = link_to 'Cancel', '#', class: 'cancel-question-link btn btn-secondary btn-sm', remote: true

app/views/questions/_form_fields.html.slim
p
  .d-inline-block.me-2
    = f.label :title, 'Your question'
  .d-inline-block.me-2
    = f.text_field :title
  p
    .d-inline-block.me-2
      = f.label :body, 'Details'
    .d-inline-block.me-2
      = f.text_area :body
  p
    .d-inline-block.me-2
      = f.label :files, 'Attach files'
    .d-inline-block.me-2
      = f.file_field :files, multiple: true, direct_upload: true
  p id='links'
    = f.fields_for :links do |link|
  .add_link
    = link_to_add_association 'Add link', f, :links,
                                             partial: 'links/link_fields',
                                             class: 'btn btn-outline-info btn-sm'

app/views/questions/_question.html.slim
- cache [current_user.present?, @question] do
  h1= question.title
  .fs-5
    = question.body
  p.fst-italic.text-secondary
    = "Question by #{question.user.email}"

  div class="question-#{question.id}-attachments"
    - if question.files.attached? || !question.links.count.nil?
      .attachment-header
        = 'Attached files and links:'
      p= render 'shared/attachments', resource: question

  .reward
    p= render 'rewards/question_reward', question: question

  b= 'Rating: '
  .rating
    = render 'shared/rating', resource: question

- if current_user && can?(:update, question)
  .question-errors
    = render 'shared/errors', resource: question

  .edit-question-form
    p= render 'questions/edit_form', question: question

  div class='btn-group' role='group'
    = link_to 'Edit question', '#', class: 'edit-question-link btn btn-outline-success btn-sm'

    = link_to 'Delete question', question_path(question),
                                method: :delete,
                                data: { confirm: 'Are you sure?' },
                                class: 'btn btn-outline-dark btn-sm'

- if current_user && can?(:create, Subscription)
  p= render 'subscriptions/subscription', question: question

div class="question-#{question.id}-comments"
  = render 'comments/comments', resource: question

app/views/questions/index.html.slim
p= link_to 'Ask question', new_question_path, class: 'btn btn-success btn-sm'

h1= 'All questions'

table class='questions table text-center'
  thead class="thead"
    tr
      th Title
      th Body
      th Reward
      th Actions
  - @questions.each do |question|
    tr id="#{question.id}"
      td= question.title
      td= question.body
      td
        - if question.reward.present?
          = image_tag question.reward.image.url, size: "50x50", alt: question.reward.title
      td= link_to 'Show answers', question, class: 'btn btn-warning btn-sm'

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question

= form_with model: @question, local: true do |f|
  = render 'form_fields', f: f

  p Assign reward:
  p= render 'rewards/form', f: f

  = f.submit 'Ask', class: 'btn btn-success btn-sm'

app/views/questions/show.html.slim
- cache_unless current_user&.admin?, [current_user.present?, @question] do
  .question
    = render @question
  .text-center
    h3= 'Answers on question'
  .answers
    .answer-errors
      = render 'shared/errors', resource: @new_answer
    - if @question.answers.first.persisted?
      .best
        - if @question.best_answer
          = render 'answers/best_answer', resource: @question.best_answer
      table class='table text-center'
        thead class='thead'
          tr
            th= 'Rating'
            th= 'Answer'
            th= 'Files and links'
            th colspan=4
              = 'Actions'
        = render @question.other_answers
    - else
      h5= 'Be the first to leave an answer'

  - unless current_user
    p.subtitle.fst-italic.text-secondary
      = 'If you want to leave your answer you must '
      = link_to 'log in', new_user_session_path

  - if can?(:create, Answer)
    .new-answer
      .errors
        = render 'shared/errors', resource: @new_answer
      = render 'answers/form', resource: @new_answer

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');
$('.flash-messages').html('<%= render 'shared/flash_messages' %>');

<% if !@question.errors.present? %>
  $('.question').html('<%= j render @question %>');
  location.reload()
<% end %>