config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
      delete :cancel_vote
    end
  end

  concern :commentable do
    resources :comments, only: %i[create destroy], shallow: true
  end

  resources :questions, concerns: %i[votable commentable] do
    resources :answers, concerns: %i[votable commentable], except: :index, shallow: true do
      member do
        patch :best
      end
    end
    resources :subscriptions, only: %i[create destroy], shallow: true
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: %i[index destroy]

  root to: "questions#index"

  get '/email', to: 'users#email'
  post '/set_email', to: 'users#set_email'

  get '/search', to: 'search#search'

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
        resources :users, only: :index do
            get :me, on: :collection
        end

        resources :questions, only: %i[index show create update destroy] do
          resources :answers, only: %i[index show create update destroy], shallow: true
        end
    end
  end
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :question, touch: true
  belongs_to :user, optional: true

  has_one_attached :image

  validates :title, presence: true
  validates :image, attached: true, content_type: %w[jpg jpeg png]
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  include ActiveStorage::SetCurrent

  before_action :authenticate_user!, except: :index

  authorize_resource

  def index
    @rewards = current_user&.rewards
  end

  def destroy
    @reward = Reward.find(params[:id])
    @reward.destroy
    flash.now.notice = 'Question reward was removed.'
  end
end

app/views/rewards/_form.html.slim
= f.fields_for :reward do |r|
  .d-inline-block.me-2
    = r.label :title, 'Reward title'
  .d-inline-block.me-4
    = r.text_field :title
  .d-inline-block.me-2
    = r.label :image, 'Image'
  .d-inline-block.me-4
    = r.file_field :image

app/views/rewards/_question_reward.html.slim
- if question.reward.present?
  .d-inline-block.me-2
    b= 'Reward: '
  .d-inline-block.me-2
    = question.reward.title
  .d-inline-block.me-4
    = image_tag question.reward.image.url, size: "50x50", alt: question.reward.title
  .d-inline-block.me-4
    - if current_user && can?(:destroy, question.reward)
      = link_to 'Delete the reward', reward_path(question.reward),
              method: :delete,
              remote: true,
              class: 'delete-reward btn btn-outline-dark btn-sm d-none',
              data: { confirm: 'Are you sure?' }

app/views/rewards/_reward.html.slim
tr
  td= reward.question.title
  td= reward.title
  td= image_tag reward.image.url, size: "50x50", alt: reward.title

app/views/rewards/destroy.js.erb
<% if !@reward.persisted? %>
  $('.flash-messages').html('<%= render 'shared/flash_messages' %>');
  $('.question .reward').remove()
  $('#question_reward_attributes_title').val('');
<% end %>

app/views/rewards/index.html.slim
h1= 'My rewards'

table class='table table-bordered text-center'
  thead class='thead'
    tr
      th Question title
      th Reward title
      th Image
  - @rewards.each do |reward|
    = render @rewards