config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
      delete :cancel_vote
    end
  end

  concern :commentable do
    resources :comments, only: %i[create destroy], shallow: true
  end

  resources :questions, concerns: %i[votable commentable] do
    resources :answers, concerns: %i[votable commentable], except: :index, shallow: true do
      member do
        patch :best
      end
    end
    resources :subscriptions, only: %i[create destroy], shallow: true
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: %i[index destroy]

  root to: "questions#index"

  get '/email', to: 'users#email'
  post '/set_email', to: 'users#set_email'

  get '/search', to: 'search#search'

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
        resources :users, only: :index do
            get :me, on: :collection
        end

        resources :questions, only: %i[index show create update destroy] do
          resources :answers, only: %i[index show create update destroy], shallow: true
        end
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  has_many :links, dependent: :destroy, as: :linkable

  belongs_to :question, touch: true
  belongs_to :user

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  validates :body, presence: true

  after_create :send_notifications

  def mark_as_best
    transaction do
      question.update!(best_answer_id: id)
      question.reward&.update!(user: user)
    end
  end

  def unmark_as_best
    transaction do
      question.update!(best_answer_id: nil)
      question.reward&.update!(user: nil)
    end
  end

  private

  def send_notifications
    NotificationJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!
  before_action :load_answer, only: %w[update destroy best]
  before_action :load_question, only: %w[create update best destroy]

  authorize_resource

  def create
    @answer = @question.answers.new(answer_params.merge(user: current_user))

    flash.now[:notice] = 'Your answer successfully created.' if @answer.save
    publish_question('add')
  end

  def update
    return unless @answer.update(answer_params.except(:files))

    attach_files(@answer)
    flash.now[:notice] = 'Your answer was successfully edited.'
    publish_question('update')
  end

  def destroy
    @answer.unmark_as_best if @answer == @question.best_answer

    @answer.destroy
    flash.now[:notice] = 'Your answer was successfully deleted.'
    publish_question('destroy')
  end

  def best
    @answer.mark_as_best
  end

  private

  def load_question
    @question ||= params[:question_id] ? Question.with_attached_files.find(params[:question_id]) : @answer.question
  end

  def load_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :question_id, files: [], links_attributes: %i[name url id destroy])
  end

  def attach_files(answer)
    answer.files.attach(params[:answer][:files]) if params[:answer][:files].present?
  end

  def publish_question(event)
    return if @answer.errors.any?

    ActionCable.server.broadcast(
      "questions/#{@answer.question_id}",
      answer: @answer,
      links: @answer.links,
      event: event
    )
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :load_answer, only: %w[show update destroy]
  before_action :load_question, only: %w[index show create]

  authorize_resource

  def index
    @answers = @question.answers
    render json: @answers
  end

  def show
    render json: @answer
  end

  def create
    @answer = current_resource_owner.answers.new(answer_params.merge(question_id: params[:question_id]))

    if @answer.save
      render json: @answer
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def update
    if @answer.update(answer_params)
      render json: @answer
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    if @answer.destroy
      render json: @answer
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body, :question_id, links_attributes: %i[name url id])
  end

  def load_question
    @question ||= params[:question_id] ? Question.with_attached_files.find(params[:question_id]) : @answer.question
  end

  def load_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache_unless current_user&.admin?, [current_user.present?, answer] do
  - if answer.persisted?
    tr class="answer-id-#{answer.id}"
      td class='rating'
        = render 'shared/rating', resource: answer
      td
        = answer.body
      td
        div class="answer-#{answer.id}-attachments"
          = render 'shared/attachments', resource: answer

      - if current_user && can?(:update, answer)
        td
          = render 'answers/edit_form', answer: answer
        td
          div class='btn-group' role='group'
            = link_to 'Edit', '#',
                            class: 'edit-answer-link btn btn-outline-success btn-sm',
                            data: { answer_id: answer.id }

            = link_to 'Delete answer', answer_path(answer),
                                       method: :delete,
                                       remote: true,
                                       class: 'btn btn-outline-dark btn-sm',
                                       data: { confirm: 'Are you sure?' }
      - else
        td colspan=2

      - if current_user && can?(:best, answer)
        td= link_to 'Choose the best', best_answer_path(answer),
                                       method: :patch,
                                       remote: true,
                                       class: 'best-answer-link btn btn-warning btn-sm',
                                       data: { answer_id: answer.id }

      td class="answer-#{answer.id}-comments"
        = render 'comments/comments', resource: answer

app/views/answers/_best_answer.html.slim
- cache_unless current_user&.admin?, [current_user.present?, @question.best_answer] do
  h5= 'Best answer'
  div class="answer-id-#{@question.best_answer.id}"
    .d-inline-block.me-4
      = '👍'
    .d-inline-block.me-4
      = @question.best_answer.body
    .d-inline-block.me-4.text-secondary
      = "by #{@question.best_answer.user.email}"

    div class="answer-#{@question.best_answer.id}-attachments"
      p= render 'shared/attachments', resource: @question.best_answer

      div class='rating'
        b= 'Rating: '
        = render 'shared/rating', resource: @question.best_answer

      - if current_user && can?(:update, @question.best_answer)
        p= render 'answers/edit_form', answer: @question.best_answer

        div class='btn-group' role='group'
          = link_to ' Edit', '#',
                  class: 'edit-answer-link  btn btn-outline-success btn-sm',
                  remote: true,
                  data: { answer_id: @question.best_answer.id }

          = link_to ' Delete answer', answer_path(@question.best_answer),
                                      method: :delete,
                                      class: 'btn btn-outline-dark btn-sm',
                                      remote: true,
                                      data: { confirm: 'Are you sure?' }

      div class="answer-#{@question.best_answer.id}-comments"
        p= render 'comments/comments', resource: @question.best_answer

app/views/answers/_edit_form.html.slim
= form_with model: answer, local: false, html: { id: "edit-answer-#{answer.id}" }, class: 'd-none' do |f|
  p
    = f.label :body, 'Your new answer'
    = f.text_area :body
  p
    = f.label :files, 'Attach files'
    = f.file_field :files, multiple: true, direct_upload: true
  p id="links"
    = f.fields_for :links do |link|
    .add_link
      = link_to_add_association 'Add link', f, :links,
              partial: 'links/link_fields',
              class: 'btn btn-outline-info btn-sm'
  div class='btn-group' role='group'
    = f.submit 'Save', class: 'btn btn-success btn-sm'
    = link_to 'Cancel', '#',
            class: 'cancel-answer-link btn btn-secondary btn-sm',
            remote: true,
            data: { answer_id: answer.id }

app/views/answers/_form.html.slim
= form_with model: [@question, @new_answer], local: false do |f|
  p
    = f.label :body, 'Your answer'
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true
  p
    = f.fields_for :links do |l|
    .add_link
      = link_to_add_association 'Add link', f, :links,
                                                partial: 'links/link_fields',
                                                class: 'btn btn-outline-info btn-sm'
  = f.submit 'To answer', class: 'btn btn-primary btn-sm'

app/views/answers/best.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if !@answer.errors.present? && @question.best_answer %>
  $('.answers .best').html('<%= j render 'answers/best_answer', resource: @question.best_answer %>');
  $('.answers table tbody').html('<%= j render @question.other_answers %>');
<% end %>

app/views/answers/create.js.erb
$('.new-answer .errors').html('<%= render 'shared/errors', resource: @answer %>');
$('.flash-messages').html('<%= render 'shared/flash_messages' %>');

<% if @answer.persisted? %>
  <% if @question.answers.count > 1 %>
    $('.answers table tbody').append('<%= j render @answer %>');
  <% else %>
    $('.answers').html('<table class="table text-center"><thead class="thead">' +
                  '<tr><th>Rating</th><th>Answer</th><th>Files and links</th><th colspan=4>Actions</th></tr><thead>' +
                  '<tbody><%= j render @answer %></tbody></table>');
  <% end %>
  $('.new-answer #answer_body').val('');
  $('.new-answer .nested-fields input').each(function(){
    $(this).val('')
  })
<% end %>

app/views/answers/destroy.js.erb
<% if !@answer.persisted? %>
  $('.flash-messages').html('<%= render 'shared/flash_messages' %>');
  <% if !@question.best_answer %>
    $('.answers .best').html('');
  <% end %>
  <% if @question.answers.count < 1 %>
    $('.answers').html('<h5>Be the first to leave an answer</h5>');
  <% else %>
    $('.answers table tbody').html('<%= j render @question.other_answers %>');
  <% end %>
  $('.answer-errors').html('')
<% end %>

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');
$('.flash-messages').html('<%= render 'shared/flash_messages' %>');

<% if !@answer.errors.present? %>
  <% if @answer == @question.best_answer %>
    $('.answer-id-<%= @answer.id %>').replaceWith('<%= j render 'answers/best_answer', resource: @question.best_answer %>');
  <% else %>
    $('.answer-id-<%= @answer.id %>').replaceWith('<%= j render @answer %>');
  <% end %>
<% end %>