config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
      delete :cancel_vote
    end
  end

  concern :commentable do
    resources :comments, only: %i[create destroy], shallow: true
  end

  resources :questions, concerns: %i[votable commentable] do
    resources :answers, concerns: %i[votable commentable], except: :index, shallow: true do
      member do
        patch :best
      end
    end
    resources :subscriptions, only: %i[create destroy], shallow: true
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: %i[index destroy]

  root to: "questions#index"

  get '/email', to: 'users#email'
  post '/set_email', to: 'users#set_email'

  get '/search', to: 'search#search'

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
        resources :users, only: :index do
            get :me, on: :collection
        end

        resources :questions, only: %i[index show create update destroy] do
          resources :answers, only: %i[index show create update destroy], shallow: true
        end
    end
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :question, touch: true
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!

  authorize_resource

  def create
    @question = Question.find(params[:question_id])
    @subscription = current_user.subscriptions.new(question: @question) unless current_user.subscribed?(@question)

    flash.now[:notice] = 'You have successfully subscribed to updates on this question' if @subscription&.save
  end

  def destroy
    @subscription = current_user&.subscriptions&.find_by(question_id: params[:id])
    flash.now.notice = 'Your subscription was removed.' if @subscription&.destroy
  end
end

app/views/subscriptions/_subscription.html.slim
.subscription
  = link_to 'Unsubscribe to updates', subscription_path(question),
                                      method: :delete,
                                      remote: true,
                                      data: { type: :json },
                                      class: 'unsubscribe-link btn btn-secondary btn-sm',
                                      style: "#{current_user&.subscribed?(question) ? '' : 'display:none;'}"
  = link_to 'Subscribe to updates', question_subscriptions_path(question),
                                    method: :post,
                                    remote: true,
                                    data: { type: :json },
                                    class: 'subscribe-link btn btn-info btn-sm',
                                    style: "#{current_user&.subscribed?(question) ? 'display:none;' : ''}"

app/views/subscriptions/create.js.erb
<% if @subscription.persisted? %>
  $('.flash-messages').html('<%= render 'shared/flash_messages' %>');
  $('.subscribe-link, .unsubscribe-link').toggle();
<% end %>

app/views/subscriptions/destroy.js.erb
<% if !@subscription.persisted? %>
  $('.flash-messages').html('<%= render 'shared/flash_messages' %>');
  $('.subscribe-link, .unsubscribe-link').toggle();
<% end %>